#!/usr/bin/env bash
sample_id="$1"
cmake --build build/Debug
echo ""

echo "Running..."
start_time=$(date +%s%N)
mpirun --map-by socket:PE=1 --report-bindings \
    -np 2 -x OMP_NUM_THREADS=4 \
    -x OMP_PROC_BIND=close \
    ./build/Debug/hw2 \
    assets/testcases/"$sample_id".jpg \
    results/"$sample_id".jpg \
    results/"$sample_id".txt
end_time=$(date +%s%N)
elapsed_time=$(( (end_time - start_time) / 1000 )) # Convert nanoseconds to microseconds
echo "Computation time: ${elapsed_time} microseconds"
echo ""

echo "Validation:"
python3 scripts/validate.py \
    results/"$sample_id".txt \
    assets/goldens/"$sample_id".txt \
    results/"$sample_id".jpg \
    assets/goldens/"$sample_id".jpg