#!/usr/bin/env bash
source scripts/env.sh

sample_id="$1"
cmake --build build/Debug
echo ""

PE=${2:-2}
NP=${3:-4}
THREADS=${4:-6}

echo "Running..."
start_time=$(date +%s%N)
mpirun --map-by socket:PE=$PE --report-bindings \
    -np $NP -x OMP_NUM_THREADS=$THREADS \
    -x OMP_PROC_BIND=close \
    -x OMP_PLACES=cores \
    ./build/Debug/hw2 \
    assets/testcases/"$sample_id".jpg \
    results/"$sample_id".jpg \
    results/"$sample_id".txt
end_time=$(date +%s%N)
elapsed_time=$(( (end_time - start_time) / 1000 )) # Convert nanoseconds to microseconds
echo "Computation time: ${elapsed_time} microseconds"
echo ""

echo "Validation:"
python scripts/validate.py \
    results/"$sample_id".txt \
    assets/goldens/"$sample_id".txt \
    results/"$sample_id".jpg \
    assets/goldens/"$sample_id".jpg