#!/usr/bin/env bash
source scripts/env.sh

sample_id="$1"
cmake --build build/Release
echo ""

n_node=${2:-2}
n_task=${3:-4}
n_core=${4:-6}

# echo "Running..."
# start_time=$(date +%s%N)
srun -A ACD114118 \
    -N "$n_node" -n "$n_task" -c "$n_core" \
    --time=00:03:00 \
    ./build/Release/hw2 \
    assets/testcases/"$sample_id".jpg \
    results/"$sample_id".jpg \
    results/"$sample_id".txt
# end_time=$(date +%s%N)
# elapsed_time=$(( (end_time - start_time) / 1000 )) # Convert nanoseconds to microseconds
# echo "Computation time: ${elapsed_time} microseconds"
# echo ""

echo "Validation:"
python scripts/validate.py \
    results/"$sample_id".txt \
    assets/goldens/"$sample_id".txt \
    results/"$sample_id".jpg \
    assets/goldens/"$sample_id".jpg